# Generated by Django 4.0.4 on 2022-06-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_flower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='user',
        ),
    ]
